name = "ModFest 1.21"
author = "ModFest"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd58826daba2c6472e76a221348153f731e2b9f01dc9c165f17214e8c62b18a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.73"
